### ISSUE TITLE
Name rendering is truncated at ' char

### ISSUE THREAD

**Issue by Krillle** [OpenSeaMap/online_chart#107]
Names of e.g. sea areas are truncated at a ' . e.g. "Platja d'es Trenc"

**Comment by wschildbach** [comment]
Hi @Krillle , Thanks for the bug report!

Can you give more detail about this? Where would you expect those names to show up? And, could you supply a permalink to an area where you observe this bug?

**Comment by Krillle** [comment]
Hi @wschildbach.

Thanks for coming back to this. 
I worked around the problem by renaming the problematic nodes. 

Original tagging with that problem was:

seamark:type = "sea_area"
seamark:sea_area:category = "bay"
seamark:name = "Platja d'es Trenc"

You can reproduce the problem with this node histories: https://www.openstreetmap.org/node/5902197421/history
https://www.openstreetmap.org/node/5902197420/history

Permalink to openseamap with workaround name: 
http://map.openseamap.org/?zoom=17&lat=39.30469&lon=3.00443&layers=BFTFFFFFFTF0TFFFFFFFFF

**Comment by wschildbach** [comment]
Thanks, I understand now. This is a problem with the seamarks renderer.

@malcolmh , could you take a look at this?

- Wolfgang

**Comment by malcolmh** [comment]
OK, I have found the problem. It is in the "jsearch" program that extracts areas from world.osm. I am splitting strings using both single and double quote characters - hence an apostrophe is seen as string terminator.

I can try simply removing the single quote from the splits & see what happens - I will have to try some off-line tests first to check that this does not break anything.

The better solution is to re-write the code using the Java XML library instead of the short-cut method that I originally used. This may take some time!

**Comment by malcolmh** [comment]
This has now been fixed.
