### ISSUE TITLE
GEBCO layer disturbs the chart

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/online_chart#49]
Since years, the GEBCO layer makes all other layers "milky". This is due to the fact that the GEBCO tiles are rendered in a way where the land areas are white, and they are put on top of the base layer with a certain level of opacity.

Now Martin submitted a patch:
```
//GebcoDepth
layer_gebco_deeps_gwc = new OpenLayers.Layer.WMS("deeps_gwc", 
"http://osm.franken.de:8080/geoserver/gwc/service/wms",
{layers: "gebco_new", format:"image/png"},
{layerId: 6, isBaseLayer: false, visibility: false, opacity: 0.4});
```

Please can somebody integrate this code?

**Comment by ehrenfeu** [comment]
There have been a lot of things going on regarding the GEBCO layer, see e.g. the [corresponding thread on the developer's mailing list](http://sourceforge.net/p/openseamap/mailman/openseamap-develop/thread/547DFB26.1080701%40he1ix.org/#msg33102275):

* depth colouring is now working and will be deployed on the main webserver (hopefully) soon (see #55)
* marine contour shading has been adjusted to generate PNG's with transparent land areas based on the GEBCO 2014 data ([see the announcement](http://sourceforge.net/p/openseamap/mailman/message/33140770/))

Still open / new bugs:
* shallow water zones are rendered in rather dark grey, which adds an ugly dark 
region on all coasts, see e.g. Mallorca / Menorca or the German Bight (see attached image 1)
* due to the relatively low resolution of the contour shading data, and the dark grey rendering, a pretty annoying "sawtooth" effect is visible on many coastlines for zoom levels 3 through 11 (see attached image 2)

##### Image 1 (Mallorca)
![mallorca_shading_shallow_water](https://cloud.githubusercontent.com/assets/697157/5759861/0987e9ae-9cd1-11e4-9d81-619870912fcd.jpg)

##### Image 2 (Menorca)
![menorca_shading_sawtooth](https://cloud.githubusercontent.com/assets/697157/5759868/186f8b52-9cd1-11e4-8502-5bd9d971a959.jpg)
