### ISSUE TITLE
Permalink for layers does not work

### ISSUE THREAD

**Issue by pyrog** [OpenSeaMap/online_chart#90]
Affected browser versions
* Seems to be a browser independent problem.<br>(Tested with Safari, Chrome and Firefox on Mac OS X)

Description
* When creating a permalink with activated tidal layer and disable all others, the link does not activate this layer again but defaults layers are always activated (nautical marks, harbors and coordinate grid).

How to reproduce the problem
* Activate only the tidal layer
* Create permalink
* Follow the [permalink](http://map.openseamap.org/?layers=BFFFFFFFFFF0FFFTFFFFFF&zoom=9&lat=49.46331&lon=8.72797)

Expected result
* The map should be loaded and display only the **tidal** layer.<br/>`layers=BFFFFFFFFFF0FFFTFFFFFF`
<img width="656" alt="good layers" src="https://cloud.githubusercontent.com/assets/2158081/15822192/99f191b2-2bf4-11e6-858f-a5f4ffb1f9ef.png">

Result
* The layers are incorrectly activated.<br/>`layers=BFTFFFTFFTF0FFFFFFFFFF`
<img width="655" alt="bad layers" src="https://cloud.githubusercontent.com/assets/2158081/15822180/8b77e5dc-2bf4-11e6-8129-37cd4e0b45d2.png">

**Comment by aAXEe** [comment]
Thank you for the very detailed and helpfull report! It was easy to find the problem with your information.

In fact the layer parameter from the url (aka permalink) was ignored completly because I missed to change some internal number than I removed the last layer.

If the above permalink brings not up the expected result now, please reopen this issue.
